### ISSUE TITLE
Janvier's Milestone 2

### ISSUE THREAD

**Issue by kevinthrailkill** [Travel-Buddy/travel-with-friends#11]
5. Plans Page
  - [x] Display list of plans by finalized and proposed plans.
  - [x] Create a new plan to the proposed plans.
  - [x] Edit existing plan.
  - [x] Delete existing plan.
  - [ ] Display recommended plans (POI's) - section?
  - [x] Liking a plan
  - [x] For finalized plans, sort by dates.
  - [x] For proposed plans, sort by creation date
      We wanted to also sort by number of likes first, but I need to skip that for now for other more important features. I might need to either do it manually or write a background job to be executed during the query, which I don't know how to do now yet.

6.  Create/Edit Plan
  - [x] Restricted to destination's start and end date.
  - [x] Search using google autocomplete.
  - [ ] Price? - restrict to US currency.

7. Detail Plan Page
  - [x] Show additional detailed info.
